### ISSUE TITLE
Shadowban functionality

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#21]
As on tin for spam & rulebreaker control. Will cause your database sizes to continue going up, but it'll interfere with any spambots looking to annoy anyone since nobody else can see what they're saying.

**Comment by liclac** [comment]
Couldn't this potentionally misfire if this hits an user by accident? Bans are clear and can be appealed, but shadowbans could look like strange bugs to users. Especially if Heello gets the same issues as Twitter with misfiring suspensions due to report button abuse or overly aggressive spambot detection algorithms.

Could be useful as a last-resort, but some people are really hard to tell from spambots…

**Comment by katanacrimson** [comment]
@uppfinnarn works well enough for reddit and many ircd's. best not to automatically use it, but just trigger it manually for problematic user accounts and such.

**Comment by noaheverett** [comment]
Do you have a link to a specific library to use?

**Comment by katanacrimson** [comment]
Unfortunately, no - the theory behind shadowbanning is a simple one though so it should be one that can be implemented and tested in under a couple hours.  

Unless the shadowbanned user is the one that is currently logged in, content isn't displayed at all (behavior is that of file/post/ping not found). It essentially turns the user's account into an echo chamber.  Complexity of implementation depends on your own db schemas, but it should be as easy to indicate as a boolean (or additional flag on a user type, e.g. `USER_SHADOW`) on the user's row.

**Comment by katanacrimson** [comment]
As I think the details have been aired out enough as it is and the suggestion has been considered, I'm going to close this issue.
